// script.js

function addCollegeInput() {
    // Add college input fields
}

document.getElementById('choice-form').addEventListener('submit', (event) => {
    event.preventDefault();
    const formData = new FormData(event.target);
    const listBody = document.getElementById('list-body');
    listBody.innerHTML = ''; // Clear previous list

    const name = formData.get('name');
    const cutoff = formData.get('cutoff');
    const choices = formData.get('choices');
    const codes = formData.getAll('code[]');
    const departments = formData.getAll('department[]');

    let tableRows = '';
    for (let i = 0; i < choices; i++) {
        const collegeCode = codes[i];
        const department = departments[i];
        const collegeName = getCollegeName(collegeCode); // Replace with actual function to get college name

        tableRows += '<tr>';
        tableRows += '<td>' + (i + 1) + '</td>';
        tableRows += '<td>' + collegeCode + '</td>';
        tableRows += '<td>' + collegeName + '</td>';
        tableRows += '<td>' + department + '</td>';
        tableRows += '</tr>';
    }
    listBody.innerHTML = tableRows;

    // Add coder name to the output
    const coderName = 'KAYILAINATHAN';
    listBody.innerHTML += `<tr><td colspan="4">Generated by ${coderName}</td></tr>`;

    alert('Choice list generated successfully!');
});

// Function to fetch college name based on code (mock implementation)
function getCollegeName(code) {
    switch (code) {
        case '1': return 'CEG';
        case '4': return 'MIT';
        case '1315': return 'SSN';
        case '1399': return 'CIT';
        case '2006': return 'PSG';
        // Add more cases as needed
        default: return 'Unknown';
    }
}

// Download button event listener
document.getElementById('download-btn').addEventListener('click', () => {
    const tableData = [];
    const rows = document.getElementById('list-body').rows;
    for (let i = 0; i < rows.length; i++) {
        const row = [];
        for (let j = 0; j < rows[i].cells.length; j++) {
            row.push(rows[i].cells[j].textContent);
        }
        tableData.push(row.join(','));
    }

    const csvData = tableData.join('\n');
    const blob = new Blob([csvData], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'choice_list.csv';
    a.click();
});